"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'fr')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{{${param}}}`, params[param])
      })
    }
    return translation
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'HOME',
    'nav.products': 'PRODUCTS',
    'nav.about': 'ABOUT',
    'nav.contact': 'CONTACT',
    'nav.quote': 'REQUEST A QUOTE',
    
    // Hero
    'hero.title1': 'Engineering Excellence',
    'hero.title2': 'Precision Manufacturing',
    'hero.subtitle1': 'Driving Progress',
    'hero.subtitle2': 'Innovative Solutions',
    'hero.desc1': 'Explore our expertise in extrusion systems, sustainable materials, and global manufacturing innovation.',
    'hero.desc2': 'Advanced automation and cutting-edge technology for superior quality and efficiency in every project.',
    'hero.contact': 'Contact Us',
    'hero.brochure': 'Brochure',
    
    // About Page
    'about.hero.title': 'About Us',
    'about.goal.title': 'Our Goal',
    'about.goal.description': 'We exist to help you produce products that improve everyday life. Empower industries with advanced materials and precision engineering and foster innovation while ensuring environmental responsibility and sustainability in every product and process.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To be a global leader in advanced precision manufacturing technologies, shaping the future of manufacturing with innovative, sustainable, and high-performance solutions.',
    
    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.form.error': 'Failed to send message. Please try again.',
    'contact.section.query': 'Have any queries?',
    'contact.section.help': 'We\'re here to help.',
    'contact.section.stranger': 'Don\'t be a stranger!',
    'contact.section.inquiry': 'Please drop your inquiry here',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Address',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone No',
    'contact.info.hours': 'Business Hours',
    'contact.info.schedule': 'Monday - Sunday: 8:00 AM - 8:00 PM',
    'contact.success.message': 'Message sent to krimavadodariya07@gmail.com!',
    
    // Quote Page
    'quote.hero.title': 'Request Quotes',
    'quote.form.title': 'Get Your Custom Quote',
    'quote.form.selected': 'Selected Products',
    'quote.form.noProducts': 'No products selected',
    'quote.form.goToProducts': 'Go to products page to add items to your quote',
    'quote.form.contact': 'Contact Information',
    'quote.form.fullName': 'Full Name',
    'quote.form.emailAddress': 'Email Address',
    'quote.form.phoneNumber': 'Phone Number',
    'quote.form.companyName': 'Company Name',
    'quote.form.requirements': 'Additional Requirements',
    'quote.form.placeholder': 'Please describe your specific requirements, quantities, delivery timeline, etc.',
    'quote.form.submit': 'Submit Quote Request',
    'quote.form.sending': 'Sending...',
    'quote.form.success': 'Quote request sent successfully!',
    
    // Products Page
    'products.hero.title': 'Our Work',
    'products.grid.addedToQuote': '{{product}} added to quote!',
    
    // About
    'about.title': 'Who We Are',
    'about.p1': 'At Karma Mechtech, we specialize in precision CNC machining with a strong focus on quality, accuracy, and reliability. Based in Saint-Laurent, Montréal, Our facility is equipped to produce high-tolerance aluminum, steel, and custom metal components.',
    'about.p2': 'We support low-volume, complex, and prototype machining with 4-axis and 5-axis capabilities. Our team combines advanced technology with skilled craftsmanship to deliver consistent results.',
    'about.p3': 'Every part we produce undergoes thorough inspection to ensure it meets strict industrial standards. We are committed to quick turnaround times, transparent communication, and long-term customer partnerships. At Karma Mechtech, precision isn\'t just a service—it\'s our identity.',
    
    // Additional Services
    'services.title': 'What We Offer',
    'services.subtitle': 'Comprehensive Manufacturing Solutions',
    'services.cnc.title': 'CNC / VMC Machining',
    'services.cnc.desc': 'High-accuracy turning and milling for complex metal and aluminum components.',
    'services.custom.title': 'Custom Manufacturing',
    'services.custom.desc': 'Tailored precision manufacturing solutions for your specific requirements and applications.',
    'services.engineering.title': 'Engineering Support',
    'services.engineering.desc': 'Expert engineering consultation and technical support throughout your project lifecycle.',
    'services.quality.title': 'Quality Assurance',
    'services.quality.desc': 'Comprehensive quality control and testing to ensure products meet industry standards.',
    'services.delivery.title': 'Global Delivery',
    'services.delivery.desc': 'Reliable worldwide shipping and logistics support for timely project completion.',
    
    // Stats
    'stats.title': 'Custom Projects',
    'stats.desc': 'We help clients bring their ideas to life by designing and building custom solutions such as small machinery, production jigs, and specialized fixtures. Our team also offers SolidWorks design services, including 3D modeling and 2D drawing creation tailored to your requirements. Whether you need a unique tool, a custom mechanism, or a complete design-to-build service, we deliver practical and precise solutions.',
    
    // Collections
    'collections.title': 'Machined Parts Gallery',
    'collections.quote': 'Request Quote',
    'collections.specs': 'Specifications',
    'collections.category': 'General Precision Components',
    'collections.addToQuote': 'Add to Quote',
    
    // Product Names - All 31 Products
    'products.adapter.title': 'Adapter',
    'products.adgBlock.title': 'ADG Block',
    'products.angleBrackets.title': 'Angle Brackets',
    'products.barrelCoolenPlate.title': 'Barrel Coolen Plate',
    'products.bracket.title': 'Bracket',
    'products.breakerPlate2.title': 'Breaker Plate 2',
    'products.breakerPlates.title': 'Breaker Plates',
    'products.bsbHousing2.title': 'BSB Housing – 2',
    'products.bsbHousingEN8.title': 'BSB Housing EN8',
    'products.bsbHousingLarge.title': 'BSB Housing Large EN8',
    'products.bsbHousingSmall.title': 'BSB Housing Small EN8',
    'products.bsbHousingExtended.title': 'BSB Housing Extended EN8',
    'products.camAssy.title': 'CAM ASSY',
    'products.chainSprocketWheel.title': 'Chain Sprocket Wheel',
    'products.extensionConnectorPipe.title': 'Extension Connector Pipe',
    'products.coolantPlate.title': 'Coolant Plate',
    'products.flance.title': 'Flance',
    'products.indexingSleeve.title': 'Indexing Sleeve MS',
    'products.indexingSleeve2.title': 'Indexing Sleeve MS 2',
    'products.lockingPlate.title': 'Locking Plate',
    'products.motorShaft.title': 'Motor Shaft',
    'products.nutEN8.title': 'Nut EN8',
    'products.proxyMTG.title': 'Proxy MTG (Aluminum)',
    'products.proxyMTG2.title': 'Proxy MTG (Aluminum) 2',
    'products.rectPedestal.title': 'RECT Pedestal CI Casting',
    'products.rotarySleeve.title': 'Rotary Sleeve',
    'products.roundBrassBush.title': 'Round Brass Bush',
    'products.shaftCollar.title': 'Shaft Collar',
    'products.shaftTorque.title': 'Shaft, Torque',
    'products.shinifyForkNut.title': 'Shinify Fork Nut – Adjuster',
    'products.weldNeckFlange.title': 'Weld Neck Flange',
    
    // Product Descriptions - All 31 Products
    'products.adapter.description': 'High-precision adapter for industrial applications',
    'products.adgBlock.description': 'Precision-engineered ADG block component',
    'products.angleBrackets.description': 'Durable angle brackets for structural support',
    'products.barrelCoolenPlate.description': 'Cooling plate for barrel applications',
    'products.bracket.description': 'Multi-purpose bracket for mounting applications',
    'products.breakerPlate2.description': 'Advanced breaker plate design',
    'products.breakerPlates.description': 'Standard breaker plates for industrial use',
    'products.bsbHousing2.description': 'Heavy-duty BSB housing component',
    'products.bsbHousingEN8.description': 'Standard BSB housing in EN8 material',
    'products.bsbHousingLarge.description': 'Large BSB housing for heavy-duty applications',
    'products.bsbHousingSmall.description': 'Compact BSB housing solution',
    'products.bsbHousingExtended.description': 'Extended BSB housing with step design',
    'products.camAssy.description': 'Complete CAM assembly unit',
    'products.chainSprocketWheel.description': 'Precision chain sprocket wheel',
    'products.extensionConnectorPipe.description': 'Connector pipe for extension applications',
    'products.coolantPlate.description': 'Efficient coolant distribution plate',
    'products.flance.description': 'High-quality flange component',
    'products.indexingSleeve.description': 'Precision indexing sleeve',
    'products.indexingSleeve2.description': 'Advanced indexing sleeve design',
    'products.lockingPlate.description': 'Secure locking plate mechanism',
    'products.motorShaft.description': 'Precision motor shaft component',
    'products.nutEN8.description': 'Heavy-duty threaded nut',
    'products.proxyMTG.description': 'Aluminum proxy mounting component',
    'products.proxyMTG2.description': 'Enhanced aluminum proxy mounting',
    'products.rectPedestal.description': 'Rectangular pedestal casting',
    'products.rotarySleeve.description': 'High-precision rotary sleeve',
    'products.roundBrassBush.description': 'Premium brass bushing component',
    'products.shaftCollar.description': 'Precision shaft collar assembly',
    'products.shaftTorque.description': 'High-torque shaft component',
    'products.shinifyForkNut.description': 'Adjustable fork nut mechanism',
    'products.weldNeckFlange.description': 'Industrial weld neck flange',
    
    // Product Specifications - All Products
    'products.adapter.spec1': 'Length: 120 mm',
    'products.adapter.spec2': 'ID: 20 mm',
    'products.adapter.spec3': 'Material: MS',
    'products.adgBlock.spec1': 'Width: 55 mm',
    'products.adgBlock.spec2': 'Thickness: 50 mm',
    'products.adgBlock.spec3': 'Length: 75 mm',
    'products.adgBlock.spec4': 'Material: MS',
    'products.angleBrackets.spec1': 'Material: MS',
    'products.angleBrackets.spec2': 'OD: 88 mm',
    'products.angleBrackets.spec3': 'ID: 38 mm',
    'products.angleBrackets.spec4': 'Thickness: 60 mm',
    'products.barrelCoolenPlate.spec1': 'Thickness: 25 mm',
    'products.barrelCoolenPlate.spec2': 'Width: 125 mm',
    'products.barrelCoolenPlate.spec3': 'Length: 205 mm',
    'products.bracket.spec1': 'Material: MS',
    'products.bracket.spec2': 'Width: 70 mm',
    'products.bracket.spec3': 'Thickness: 38 mm',
    'products.bracket.spec4': 'Length: 25 mm',
    'products.breakerPlate2.spec1': 'Material: EN41',
    'products.breakerPlate2.spec2': 'OD: 60 mm',
    'products.breakerPlate2.spec3': 'Step OD: 40 mm',
    'products.breakerPlate2.spec4': 'Thickness: 38 mm',
    'products.breakerPlates.spec1': 'Material: EN41',
    'products.breakerPlates.spec2': 'OD: 60 mm',
    'products.breakerPlates.spec3': 'Step OD: 40 mm',
    'products.breakerPlates.spec4': 'Thickness: 38 mm',
    'products.bsbHousing2.spec1': 'Material: EN8',
    'products.bsbHousing2.spec2': 'OD: 110 mm',
    'products.bsbHousing2.spec3': 'ID: 85 mm',
    'products.bsbHousing2.spec4': 'Length: 105 mm',
    'products.bsbHousingEN8.spec1': 'Material: EN8',
    'products.bsbHousingEN8.spec2': 'OD: 100 mm',
    'products.bsbHousingEN8.spec3': 'ID: 50 mm',
    'products.bsbHousingEN8.spec4': 'Length: 100 mm',
    'products.bsbHousingLarge.spec1': 'Material: EN8',
    'products.bsbHousingLarge.spec2': 'OD: 200 mm',
    'products.bsbHousingLarge.spec3': 'ID: 110 mm',
    'products.bsbHousingLarge.spec4': 'Step OD: 90 mm',
    'products.bsbHousingLarge.spec5': 'Length: 165 mm',
    'products.bsbHousingSmall.spec1': 'OD: 100 mm',
    'products.bsbHousingSmall.spec2': 'ID: 45 mm',
    'products.bsbHousingSmall.spec3': 'Length: 100 mm',
    'products.bsbHousingExtended.spec1': 'OD: 200 mm',
    'products.bsbHousingExtended.spec2': 'ID: 110 mm',
    'products.bsbHousingExtended.spec3': 'Step ID: 90 mm',
    'products.bsbHousingExtended.spec4': 'Length: 165 mm',
    'products.chainSprocketWheel.spec1': 'Material: MS',
    'products.chainSprocketWheel.spec2': 'OD: 88 mm',
    'products.chainSprocketWheel.spec3': 'ID: 38 mm',
    'products.chainSprocketWheel.spec4': 'Thickness: 60 mm',
    'products.chainSprocketWheel.spec5': 'Length: 100 mm',
    'products.extensionConnectorPipe.spec1': 'Material: MS',
    'products.coolantPlate.spec1': 'Width: 125 mm',
    'products.coolantPlate.spec2': 'Thickness: 25 mm',
    'products.coolantPlate.spec3': 'Length: 100 mm',
    'products.flance.spec1': 'Material: EN8',
    'products.flance.spec2': 'OD: 200 mm',
    'products.flance.spec3': 'ID: 110 mm',
    'products.flance.spec4': 'Step OD: 90 mm',
    'products.flance.spec5': 'Length: 50 mm',
    'products.indexingSleeve.spec1': 'OD: 88 mm',
    'products.indexingSleeve.spec2': 'ID: 42 mm',
    'products.indexingSleeve.spec3': 'Length: 45 mm',
    'products.indexingSleeve2.spec1': 'OD: 88 mm',
    'products.indexingSleeve2.spec2': 'ID: 42 mm',
    'products.indexingSleeve2.spec3': 'Length: 45 mm',
    'products.lockingPlate.spec1': 'Width: 50 mm',
    'products.lockingPlate.spec2': 'Thickness: 18 mm',
    'products.lockingPlate.spec3': 'Length: 105 mm',
    'products.lockingPlate.spec4': 'Material: MS',
    'products.motorShaft.spec1': 'Material: MS',
    'products.nutEN8.spec1': 'OD: 110 mm',
    'products.nutEN8.spec2': 'ID: M60 Thread',
    'products.nutEN8.spec3': 'Length: 20 mm',
    'products.proxyMTG.spec1': 'Material: MS',
    'products.proxyMTG.spec2': 'Width: 20 mm',
    'products.proxyMTG.spec3': 'Thickness: 24 mm',
    'products.proxyMTG.spec4': 'Length: 50 mm',
    'products.rectPedestal.spec1': 'Material: MS',
    'products.rectPedestal.spec2': 'Length: 105 mm',
    'products.rectPedestal.spec3': 'Thickness: 25 mm',
    'products.rectPedestal.spec4': 'Width: 75 mm',
    'products.rotarySleeve.spec1': 'Material: EN418',
    'products.rotarySleeve.spec2': 'OD: 70 mm',
    'products.rotarySleeve.spec3': 'Step OD: 38 mm',
    'products.rotarySleeve.spec4': 'ID: 25 mm',
    'products.roundBrassBush.spec1': 'Material: Brass',
    'products.roundBrassBush.spec2': 'OD: 35 mm',
    'products.roundBrassBush.spec3': 'ID: 25 mm',
    'products.roundBrassBush.spec4': 'Length: 750 mm',
    'products.roundBrassBush.spec5': 'Thickness: 9 mm',
    'products.shaftCollar.spec1': 'Material: EN418',
    'products.shaftCollar.spec2': 'OD: 88 mm',
    'products.shaftCollar.spec3': 'Thickness: 45 mm',
    'products.shaftCollar.spec4': 'ID: 42 mm',
    'products.shaftTorque.spec1': 'Material: MS',
    'products.shaftTorque.spec2': 'Length: 75 mm',
    'products.shaftTorque.spec3': 'ID: 15 mm',
    'products.shinifyForkNut.spec1': 'Material: MS',
    'products.shinifyForkNut.spec2': 'ID: 18 mm',
    'products.shinifyForkNut.spec3': 'Step OD: 90 mm',
    'products.shinifyForkNut.spec4': 'Length: 120 mm',
    'products.weldNeckFlange.spec1': 'Material: ASTM A105',
    'products.weldNeckFlange.spec2': 'Size/Diameter: 15 inch',
    'products.weldNeckFlange.spec3': 'Thickness: 25 mm',
    
    // Why Choose Us
    'why.title': 'Six Reasons For People For Choosing Us',
    'why.quality': 'Quality Material',
    'why.quality.desc': 'Premium grade materials ensuring durability and performance',
    'why.accredited': 'Accredited',
    'why.accredited.desc': 'Certified quality management systems and industry standards',
    'why.workers': 'Trained Workers',
    'why.workers.desc': 'Skilled professionals with extensive manufacturing expertise',
    'why.global': 'Global Reach',
    'why.global.desc': 'International presence with worldwide shipping capabilities',
    'why.response': 'Quick Response',
    'why.response.desc': 'Fast turnaround times and responsive customer service',
    'why.sustainability': 'Sustainability Focus',
    'why.sustainability.desc': 'Environmentally conscious manufacturing and recycling practices',
    
    // Footer
    'footer.company': 'Karma Technologies Mecaniques',
    'footer.address': 'Saint-Laurent, Montréal, QC',
    'footer.phone': 'Phone',
    'footer.email': 'Email',
    'footer.follow': 'Follow Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.useful.links': 'Useful Links',
    'footer.get.in.touch': 'Get In Touch',
    'footer.location': 'Location',
    'footer.founders': 'Founders',
    'footer.address.full': '2634 Rue Sabourin, Saint-Laurent, QC, Canada H4S 1M2',
    'footer.address.label': 'Address',
    'footer.yash': 'Yash Sutariya',
    'footer.paras': 'Paras Limbasiya',
    'footer.tagline': 'Precision. Performance. Perfection.',
    'footer.copyright': '© Copyright KARMA Technologies Mécaniques Inc. All Rights Reserved',
    'footer.designed': 'Designed & Developed by',
    
    // Specifications Terms
    'spec.material': 'Material',
    'spec.od': 'OD',
    'spec.id': 'ID',
    'spec.length': 'Length',
    'spec.thickness': 'Thickness',
    'spec.width': 'Width',
    'spec.step.od': 'Step OD'
  },
  fr: {
    // Navigation
    'nav.home': 'ACCUEIL',
    'nav.products': 'PRODUITS',
    'nav.about': 'À PROPOS',
    'nav.contact': 'CONTACT',
    'nav.quote': 'DEMANDER UN DEVIS',
    
    // Hero
    'hero.title1': 'Excellence en Ingénierie',
    'hero.title2': 'Fabrication de Précision',
    'hero.subtitle1': 'Conduire le Progrès',
    'hero.subtitle2': 'Solutions Innovantes',
    'hero.desc1': 'Explorez notre expertise en systèmes d\'extrusion, matériaux durables et innovation manufacturière mondiale.',
    'hero.desc2': 'Automatisation avancée et technologie de pointe pour une qualité supérieure et une efficacité dans chaque projet.',
    'hero.contact': 'Nous Contacter',
    'hero.brochure': 'Brochure',
    
    // About Page
    'about.hero.title': 'À Propos de Nous',
    'about.goal.title': 'Notre Objectif',
    'about.goal.description': 'Nous existons pour vous aider à produire des produits qui améliorent la vie quotidienne. Autonomiser les industries avec des matériaux avancés et une ingénierie de précision et favoriser l\'innovation tout en assurant la responsabilité environnementale et la durabilité dans chaque produit et processus.',
    'about.vision.title': 'Notre Vision',
    'about.vision.description': 'Être un leader mondial dans les technologies de fabrication de précision avancées, façonnant l\'avenir de la fabrication avec des solutions innovantes, durables et haute performance.',
    
    // Contact Page
    'contact.hero.title': 'Nous Contacter',
    'contact.form.name': 'Nom',
    'contact.form.email': 'Courriel',
    'contact.form.subject': 'Sujet',
    'contact.form.message': 'Message',
    'contact.form.send': 'Envoyer le Message',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.success': 'Message envoyé avec succès!',
    'contact.form.error': 'Échec de l\'envoi du message. Veuillez réessayer.',
    'contact.section.query': 'Avez-vous des questions?',
    'contact.section.help': 'Nous sommes là pour vous aider.',
    'contact.section.stranger': 'Ne soyez pas un étranger!',
    'contact.section.inquiry': 'Veuillez déposer votre demande ici',
    'contact.info.title': 'Informations de Contact',
    'contact.info.address': 'Adresse',
    'contact.info.email': 'Courriel',
    'contact.info.phone': 'Téléphone',
    'contact.info.hours': 'Heures d\'Ouverture',
    'contact.info.schedule': 'Lundi - Dimanche: 8h00 - 20h00',
    'contact.success.message': 'Message envoyé à krimavadodariya07@gmail.com!',
    
    // Quote Page
    'quote.hero.title': 'Demander des Devis',
    'quote.form.title': 'Obtenez Votre Devis Personnalisé',
    'quote.form.selected': 'Produits Sélectionnés',
    'quote.form.noProducts': 'Aucun produit sélectionné',
    'quote.form.goToProducts': 'Allez à la page des produits pour ajouter des articles à votre devis',
    'quote.form.contact': 'Informations de Contact',
    'quote.form.fullName': 'Nom Complet',
    'quote.form.emailAddress': 'Adresse Courriel',
    'quote.form.phoneNumber': 'Numéro de Téléphone',
    'quote.form.companyName': 'Nom de l\'Entreprise',
    'quote.form.requirements': 'Exigences Supplémentaires',
    'quote.form.placeholder': 'Veuillez décrire vos exigences spécifiques, quantités, délais de livraison, etc.',
    'quote.form.submit': 'Soumettre la Demande de Devis',
    'quote.form.sending': 'Envoi en cours...',
    'quote.form.success': 'Demande de devis envoyée avec succès!',
    
    // Products Page
    'products.hero.title': 'Notre Travail',
    'products.grid.addedToQuote': '{{product}} ajouté au devis!',
    
    // About
    'about.title': 'Qui Nous Sommes',
    'about.p1': 'Chez Karma Mechtech, nous nous spécialisons dans l\'usinage CNC de précision avec un fort accent sur la qualité, la précision et la fiabilité. Basés à Saint-Laurent, Montréal, notre installation est équipée pour produire des composants en aluminium, acier et métaux personnalisés à haute tolérance.',
    'about.p2': 'Nous supportons l\'usinage de faible volume, complexe et de prototype avec des capacités 4 axes et 5 axes. Notre équipe combine technologie avancée et savoir-faire qualifié pour livrer des résultats cohérents.',
    'about.p3': 'Chaque pièce que nous produisons subit une inspection approfondie pour s\'assurer qu\'elle répond aux normes industrielles strictes. Nous nous engageons à des délais rapides, une communication transparente et des partenariats clients à long terme. Chez Karma Mechtech, la précision n\'est pas seulement un service—c\'est notre identité.',
    
    // Additional Services
    'services.title': 'Ce Que Nous Offrons',
    'services.subtitle': 'Solutions de Fabrication Complètes',
    'services.cnc.title': 'Usinage CNC / VMC',
    'services.cnc.desc': 'Tournage et fraisage de haute précision pour composants métalliques et en aluminium complexes.',
    'services.custom.title': 'Fabrication Personnalisée',
    'services.custom.desc': 'Solutions de fabrication de précision sur mesure pour vos exigences et applications spécifiques.',
    'services.engineering.title': 'Support Ingénierie',
    'services.engineering.desc': 'Consultation d\'ingénierie experte et support technique tout au long du cycle de vie de votre projet.',
    'services.quality.title': 'Assurance Qualité',
    'services.quality.desc': 'Contrôle qualité complet et tests pour s\'assurer que les produits répondent aux normes industrielles.',
    'services.delivery.title': 'Livraison Mondiale',
    'services.delivery.desc': 'Support d\'expédition et logistique mondial fiable pour une completion de projet en temps opportun.',
    
    // Stats
    'stats.title': 'Projets Personnalisés',
    'stats.desc': 'Nous aidons les clients à donner vie à leurs idées en concevant et construisant des solutions personnalisées telles que de petites machines, gabarits de production et fixations spécialisées. Notre équipe offre également des services de conception SolidWorks, incluant la modélisation 3D et la création de dessins 2D adaptés à vos exigences. Que vous ayez besoin d\'un outil unique, d\'un mécanisme personnalisé ou d\'un service complet de conception à construction, nous livrons des solutions pratiques et précises.',
    
    // Collections
    'collections.title': 'Galerie de Pièces Usinées',
    'collections.quote': 'Demander un Devis',
    'collections.specs': 'Spécifications',
    'collections.category': 'Composants de Précision Générale',
    'collections.addToQuote': 'Ajouter au Devis',
    
    // Product Names - All 31 Products
    'products.adapter.title': 'Adaptateur',
    'products.adgBlock.title': 'Bloc ADG',
    'products.angleBrackets.title': 'Supports d\'Angle',
    'products.barrelCoolenPlate.title': 'Plaque de Refroidissement Cylindre',
    'products.bracket.title': 'Support',
    'products.breakerPlate2.title': 'Plaque de Rupture 2',
    'products.breakerPlates.title': 'Plaques de Rupture',
    'products.bsbHousing2.title': 'Boîtier BSB – 2',
    'products.bsbHousingEN8.title': 'Boîtier BSB EN8',
    'products.bsbHousingLarge.title': 'Grand Boîtier BSB EN8',
    'products.bsbHousingSmall.title': 'Petit Boîtier BSB EN8',
    'products.bsbHousingExtended.title': 'Boîtier BSB Étendu EN8',
    'products.camAssy.title': 'Assemblage CAM',
    'products.chainSprocketWheel.title': 'Roue à Pignon de Chaîne',
    'products.extensionConnectorPipe.title': 'Tuyau Connecteur d\'Extension',
    'products.coolantPlate.title': 'Plaque de Refroidissement',
    'products.flance.title': 'Bride',
    'products.indexingSleeve.title': 'Manchon d\'Indexation MS',
    'products.indexingSleeve2.title': 'Manchon d\'Indexation MS 2',
    'products.lockingPlate.title': 'Plaque de Verrouillage',
    'products.motorShaft.title': 'Arbre Moteur',
    'products.nutEN8.title': 'Écrou EN8',
    'products.proxyMTG.title': 'Montage Proxy (Aluminium)',
    'products.proxyMTG2.title': 'Montage Proxy (Aluminium) 2',
    'products.rectPedestal.title': 'Piédestal Rectangulaire CI Coulé',
    'products.rotarySleeve.title': 'Manchon Rotatif',
    'products.roundBrassBush.title': 'Bague en Laiton Ronde',
    'products.shaftCollar.title': 'Collier d\'Arbre',
    'products.shaftTorque.title': 'Arbre, Couple',
    'products.shinifyForkNut.title': 'Écrou de Fourche Shinify – Ajusteur',
    'products.weldNeckFlange.title': 'Bride à Souder',
    
    // Product Descriptions - All 31 Products
    'products.adapter.description': 'Adaptateur de haute précision pour applications industrielles',
    'products.adgBlock.description': 'Composant de bloc ADG d\'ingénierie de précision',
    'products.angleBrackets.description': 'Supports d\'angle durables pour support structurel',
    'products.barrelCoolenPlate.description': 'Plaque de refroidissement pour applications de cylindre',
    'products.bracket.description': 'Support polyvalent pour applications de montage',
    'products.breakerPlate2.description': 'Conception avancée de plaque de rupture',
    'products.breakerPlates.description': 'Plaques de rupture standard pour usage industriel',
    'products.bsbHousing2.description': 'Composant de boîtier BSB robuste',
    'products.bsbHousingEN8.description': 'Boîtier BSB standard en matériau EN8',
    'products.bsbHousingLarge.description': 'Grand boîtier BSB pour applications lourdes',
    'products.bsbHousingSmall.description': 'Solution de boîtier BSB compact',
    'products.bsbHousingExtended.description': 'Boîtier BSB étendu avec conception à étages',
    'products.camAssy.description': 'Unité d\'assemblage CAM complète',
    'products.chainSprocketWheel.description': 'Roue à pignon de chaîne de précision',
    'products.extensionConnectorPipe.description': 'Tuyau connecteur pour applications d\'extension',
    'products.coolantPlate.description': 'Plaque de distribution de liquide de refroidissement efficace',
    'products.flance.description': 'Composant de bride de haute qualité',
    'products.indexingSleeve.description': 'Manchon d\'indexation de précision',
    'products.indexingSleeve2.description': 'Conception avancée de manchon d\'indexation',
    'products.lockingPlate.description': 'Mécanisme de plaque de verrouillage sécurisé',
    'products.motorShaft.description': 'Composant d\'arbre moteur de précision',
    'products.nutEN8.description': 'Écrou fileté robuste',
    'products.proxyMTG.description': 'Composant de montage proxy en aluminium',
    'products.proxyMTG2.description': 'Montage proxy en aluminium amélioré',
    'products.rectPedestal.description': 'Coulée de piédestal rectangulaire',
    'products.rotarySleeve.description': 'Manchon rotatif de haute précision',
    'products.roundBrassBush.description': 'Composant de bague en laiton premium',
    'products.shaftCollar.description': 'Assemblage de collier d\'arbre de précision',
    'products.shaftTorque.description': 'Composant d\'arbre à couple élevé',
    'products.shinifyForkNut.description': 'Mécanisme d\'écrou de fourche ajustable',
    'products.weldNeckFlange.description': 'Bride à souder industrielle',
    
    // Product Specifications - All Products
    'products.adapter.spec1': 'Longueur: 120 mm',
    'products.adapter.spec2': 'DI: 20 mm',
    'products.adapter.spec3': 'Matériau: MS',
    'products.adgBlock.spec1': 'Largeur: 55 mm',
    'products.adgBlock.spec2': 'Épaisseur: 50 mm',
    'products.adgBlock.spec3': 'Longueur: 75 mm',
    'products.adgBlock.spec4': 'Matériau: MS',
    'products.angleBrackets.spec1': 'Matériau: MS',
    'products.angleBrackets.spec2': 'DE: 88 mm',
    'products.angleBrackets.spec3': 'DI: 38 mm',
    'products.angleBrackets.spec4': 'Épaisseur: 60 mm',
    'products.barrelCoolenPlate.spec1': 'Épaisseur: 25 mm',
    'products.barrelCoolenPlate.spec2': 'Largeur: 125 mm',
    'products.barrelCoolenPlate.spec3': 'Longueur: 205 mm',
    'products.bracket.spec1': 'Matériau: MS',
    'products.bracket.spec2': 'Largeur: 70 mm',
    'products.bracket.spec3': 'Épaisseur: 38 mm',
    'products.bracket.spec4': 'Longueur: 25 mm',
    'products.breakerPlate2.spec1': 'Matériau: EN41',
    'products.breakerPlate2.spec2': 'DE: 60 mm',
    'products.breakerPlate2.spec3': 'DE Étage: 40 mm',
    'products.breakerPlate2.spec4': 'Épaisseur: 38 mm',
    'products.breakerPlates.spec1': 'Matériau: EN41',
    'products.breakerPlates.spec2': 'DE: 60 mm',
    'products.breakerPlates.spec3': 'DE Étage: 40 mm',
    'products.breakerPlates.spec4': 'Épaisseur: 38 mm',
    'products.bsbHousing2.spec1': 'Matériau: EN8',
    'products.bsbHousing2.spec2': 'DE: 110 mm',
    'products.bsbHousing2.spec3': 'DI: 85 mm',
    'products.bsbHousing2.spec4': 'Longueur: 105 mm',
    'products.bsbHousingEN8.spec1': 'Matériau: EN8',
    'products.bsbHousingEN8.spec2': 'DE: 100 mm',
    'products.bsbHousingEN8.spec3': 'DI: 50 mm',
    'products.bsbHousingEN8.spec4': 'Longueur: 100 mm',
    'products.bsbHousingLarge.spec1': 'Matériau: EN8',
    'products.bsbHousingLarge.spec2': 'DE: 200 mm',
    'products.bsbHousingLarge.spec3': 'DI: 110 mm',
    'products.bsbHousingLarge.spec4': 'DE Étage: 90 mm',
    'products.bsbHousingLarge.spec5': 'Longueur: 165 mm',
    'products.bsbHousingSmall.spec1': 'DE: 100 mm',
    'products.bsbHousingSmall.spec2': 'DI: 45 mm',
    'products.bsbHousingSmall.spec3': 'Longueur: 100 mm',
    'products.bsbHousingExtended.spec1': 'DE: 200 mm',
    'products.bsbHousingExtended.spec2': 'DI: 110 mm',
    'products.bsbHousingExtended.spec3': 'DI Étage: 90 mm',
    'products.bsbHousingExtended.spec4': 'Longueur: 165 mm',
    'products.chainSprocketWheel.spec1': 'Matériau: MS',
    'products.chainSprocketWheel.spec2': 'DE: 88 mm',
    'products.chainSprocketWheel.spec3': 'DI: 38 mm',
    'products.chainSprocketWheel.spec4': 'Épaisseur: 60 mm',
    'products.chainSprocketWheel.spec5': 'Longueur: 100 mm',
    'products.extensionConnectorPipe.spec1': 'Matériau: MS',
    'products.coolantPlate.spec1': 'Largeur: 125 mm',
    'products.coolantPlate.spec2': 'Épaisseur: 25 mm',
    'products.coolantPlate.spec3': 'Longueur: 100 mm',
    'products.flance.spec1': 'Matériau: EN8',
    'products.flance.spec2': 'DE: 200 mm',
    'products.flance.spec3': 'DI: 110 mm',
    'products.flance.spec4': 'DE Étage: 90 mm',
    'products.flance.spec5': 'Longueur: 50 mm',
    'products.indexingSleeve.spec1': 'DE: 88 mm',
    'products.indexingSleeve.spec2': 'DI: 42 mm',
    'products.indexingSleeve.spec3': 'Longueur: 45 mm',
    'products.indexingSleeve2.spec1': 'DE: 88 mm',
    'products.indexingSleeve2.spec2': 'DI: 42 mm',
    'products.indexingSleeve2.spec3': 'Longueur: 45 mm',
    'products.lockingPlate.spec1': 'Largeur: 50 mm',
    'products.lockingPlate.spec2': 'Épaisseur: 18 mm',
    'products.lockingPlate.spec3': 'Longueur: 105 mm',
    'products.lockingPlate.spec4': 'Matériau: MS',
    'products.motorShaft.spec1': 'Matériau: MS',
    'products.nutEN8.spec1': 'DE: 110 mm',
    'products.nutEN8.spec2': 'DI: Filetage M60',
    'products.nutEN8.spec3': 'Longueur: 20 mm',
    'products.proxyMTG.spec1': 'Matériau: MS',
    'products.proxyMTG.spec2': 'Largeur: 20 mm',
    'products.proxyMTG.spec3': 'Épaisseur: 24 mm',
    'products.proxyMTG.spec4': 'Longueur: 50 mm',
    'products.rectPedestal.spec1': 'Matériau: MS',
    'products.rectPedestal.spec2': 'Longueur: 105 mm',
    'products.rectPedestal.spec3': 'Épaisseur: 25 mm',
    'products.rectPedestal.spec4': 'Largeur: 75 mm',
    'products.rotarySleeve.spec1': 'Matériau: EN418',
    'products.rotarySleeve.spec2': 'DE: 70 mm',
    'products.rotarySleeve.spec3': 'DE Étage: 38 mm',
    'products.rotarySleeve.spec4': 'DI: 25 mm',
    'products.roundBrassBush.spec1': 'Matériau: Laiton',
    'products.roundBrassBush.spec2': 'DE: 35 mm',
    'products.roundBrassBush.spec3': 'DI: 25 mm',
    'products.roundBrassBush.spec4': 'Longueur: 750 mm',
    'products.roundBrassBush.spec5': 'Épaisseur: 9 mm',
    'products.shaftCollar.spec1': 'Matériau: EN418',
    'products.shaftCollar.spec2': 'DE: 88 mm',
    'products.shaftCollar.spec3': 'Épaisseur: 45 mm',
    'products.shaftCollar.spec4': 'DI: 42 mm',
    'products.shaftTorque.spec1': 'Matériau: MS',
    'products.shaftTorque.spec2': 'Longueur: 75 mm',
    'products.shaftTorque.spec3': 'DI: 15 mm',
    'products.shinifyForkNut.spec1': 'Matériau: MS',
    'products.shinifyForkNut.spec2': 'DI: 18 mm',
    'products.shinifyForkNut.spec3': 'DE Étage: 90 mm',
    'products.shinifyForkNut.spec4': 'Longueur: 120 mm',
    'products.weldNeckFlange.spec1': 'Matériau: ASTM A105',
    'products.weldNeckFlange.spec2': 'Taille/Diamètre: 15 pouces',
    'products.weldNeckFlange.spec3': 'Épaisseur: 25 mm',
    
    // Why Choose Us
    'why.title': 'Six Raisons Pour Lesquelles Les Gens Nous Choisissent',
    'why.quality': 'Matériau de Qualité',
    'why.quality.desc': 'Matériaux de qualité supérieure assurant durabilité et performance',
    'why.accredited': 'Accrédité',
    'why.accredited.desc': 'Systèmes de gestion de qualité certifiés et normes industrielles',
    'why.workers': 'Travailleurs Formés',
    'why.workers.desc': 'Professionnels qualifiés avec une expertise manufacturière étendue',
    'why.global': 'Portée Mondiale',
    'why.global.desc': 'Présence internationale avec capacités d\'expédition mondiale',
    'why.response': 'Réponse Rapide',
    'why.response.desc': 'Délais rapides et service client réactif',
    'why.sustainability': 'Focus Durabilité',
    'why.sustainability.desc': 'Fabrication respectueuse de l\'environnement et pratiques de recyclage',
    
    // Footer
    'footer.company': 'Karma Technologies Mécaniques',
    'footer.address': 'Saint-Laurent, Montréal, QC',
    'footer.phone': 'Téléphone',
    'footer.email': 'Courriel',
    'footer.follow': 'Suivez-Nous',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions de Service',
    'footer.useful.links': 'Liens Utiles',
    'footer.get.in.touch': 'Nous Contacter',
    'footer.location': 'Emplacement',
    'footer.founders': 'Fondateurs',
    'footer.address.full': '2634 Rue Sabourin, Saint-Laurent, QC, Canada H4S 1M2',
    'footer.address.label': 'Adresse',
    'footer.yash': 'Yash Sutariya',
    'footer.paras': 'Paras Limbasiya',
    'footer.tagline': 'Précision. Performance. Perfection.',
    'footer.copyright': '© Copyright KARMA Technologies Mécaniques Inc. Tous Droits Réservés',
    'footer.designed': 'Conçu et Développé par',
    
    // Specifications Terms
    'spec.material': 'Matériau',
    'spec.od': 'DE',
    'spec.id': 'DI',
    'spec.length': 'Longueur',
    'spec.thickness': 'Épaisseur',
    'spec.width': 'Largeur',
    'spec.step.od': 'DE Étage'
  }
}